{"failedCount":1,"prefixedPath":"src\/test\/java\/blood_type\/blood_type_all.feature","packageQualifiedName":"src.test.java.blood_type.blood_type_all","loopIndex":-1,"relativePath":"src\/test\/java\/blood_type\/blood_type_all.feature","scenarioResults":[{"sectionIndex":0,"stepResults":[{"result":{"nanos":2004887200,"millis":2004.8872,"status":"passed"},"step":{"background":true,"line":5,"prefix":"*","index":0,"text":"call read(\"..\/user\/token\/users-token-post.feature@token\")"},"callResults":[{"failedCount":0,"prefixedPath":"src\/test\/java\/blood_type\/..\/user\/token\/users-token-post.feature","packageQualifiedName":"src.test.java.blood_type.user.token.users-token-post","loopIndex":-1,"relativePath":"src\/test\/java\/blood_type\/..\/user\/token\/users-token-post.feature","scenarioResults":[{"sectionIndex":0,"stepResults":[{"result":{"nanos":5914400,"millis":5.9144,"status":"passed"},"step":{"line":6,"prefix":"Given","index":0,"text":"url \"https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/users\/token\/\""}},{"result":{"nanos":118567400,"millis":118.5674,"status":"passed"},"step":{"line":7,"prefix":"And","index":1,"text":"request {\"user\": \"ruben1\", \"password\": \"ruben123\"}"}},{"result":{"nanos":1625905900,"millis":1625.9059,"status":"passed"},"step":{"line":8,"prefix":"When","index":2,"text":"method post"},"stepLog":"17:27:18.233 request:\n1 > POST https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/users\/token\/\n1 > Content-Type: application\/json; charset=UTF-8\n1 > Content-Length: 39\n1 > Host: funcoeback-dev-ceqh.3.us-1.fl0.io\n1 > Connection: Keep-Alive\n1 > User-Agent: Apache-HttpClient\/4.5.13 (Java\/21.0.2)\n1 > Accept-Encoding: gzip,deflate\n{\"user\":\"ruben1\",\"password\":\"ruben123\"}\n\n17:27:19.504 response time in milliseconds: 1269\n1 < 200\n1 < date: Mon, 04 Mar 2024 22:27:19 GMT\n1 < server: envoy\n1 < content-length: 166\n1 < content-type: application\/json\n1 < x-envoy-upstream-service-time: 744\n{\"access_token\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoicnViZW4xIiwiZXhwaXJlcyI6MTcwOTY5MTI0MC4zNDA3Mjk3fQ.Rn5BI-Nk9wyi7Pr21eTnSYU9htOB0rzO34x0HPKwrXE\"}\n\n"},{"result":{"nanos":6330300,"millis":6.3303,"status":"passed"},"step":{"line":9,"prefix":"Then","index":3,"text":"status 200"}},{"result":{"nanos":22811000,"millis":22.811,"status":"passed"},"step":{"line":10,"prefix":"*","index":4,"text":"def token = $.access_token"}}],"line":5,"description":"","durationMillis":1779.529,"failed":false,"tags":["token"],"executorName":"main","name":"Post a token","startTime":1709591237746,"refId":"[1:5]","endTime":1709591239536,"exampleIndex":-1}],"callDepth":1,"name":"JWT Token Feature","description":"","resultDate":"2024-03-04 05:27:20 p.\u202Fm.","durationMillis":1779.529,"passedCount":1}]},{"result":{"nanos":12298300,"millis":12.2983,"status":"passed"},"step":{"background":true,"line":6,"prefix":"*","index":1,"text":"header Authorization = \"Bearer \"  + token"}},{"result":{"nanos":443100,"millis":0.4431,"status":"passed"},"step":{"line":9,"prefix":"Given","index":0,"text":"url \"https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/blood_type\/all\/\""}},{"result":{"nanos":794957000,"millis":794.957,"status":"passed"},"step":{"line":10,"prefix":"When","index":1,"text":"method get"},"stepLog":"17:27:19.553 request:\n2 > GET https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/blood_type\/all\/\n2 > Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoicnViZW4xIiwiZXhwaXJlcyI6MTcwOTY5MTI0MC4zNDA3Mjk3fQ.Rn5BI-Nk9wyi7Pr21eTnSYU9htOB0rzO34x0HPKwrXE\n2 > Host: funcoeback-dev-ceqh.3.us-1.fl0.io\n2 > Connection: Keep-Alive\n2 > User-Agent: Apache-HttpClient\/4.5.13 (Java\/21.0.2)\n2 > Accept-Encoding: gzip,deflate\n\n\n17:27:19.836 request:\n3 > GET https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/blood_type\/all\/\n3 > Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoicnViZW4xIiwiZXhwaXJlcyI6MTcwOTY5MTI0MC4zNDA3Mjk3fQ.Rn5BI-Nk9wyi7Pr21eTnSYU9htOB0rzO34x0HPKwrXE\n3 > Host: funcoeback-dev-ceqh.3.us-1.fl0.io\n3 > Connection: Keep-Alive\n3 > User-Agent: Apache-HttpClient\/4.5.13 (Java\/21.0.2)\n3 > Accept-Encoding: gzip,deflate\n\n\n17:27:20.013 request:\n4 > GET https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/blood_type\/all\/\n4 > Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoicnViZW4xIiwiZXhwaXJlcyI6MTcwOTY5MTI0MC4zNDA3Mjk3fQ.Rn5BI-Nk9wyi7Pr21eTnSYU9htOB0rzO34x0HPKwrXE\n4 > Host: funcoeback-dev-ceqh.3.us-1.fl0.io\n4 > Connection: Keep-Alive\n4 > User-Agent: Apache-HttpClient\/4.5.13 (Java\/21.0.2)\n4 > Accept-Encoding: gzip,deflate\n\n\n17:27:20.346 response time in milliseconds: 332\n4 < 500\n4 < date: Mon, 04 Mar 2024 22:27:20 GMT\n4 < server: envoy\n4 < content-length: 2600\n4 < content-type: text\/plain; charset=utf-8\n4 < x-envoy-upstream-service-time: 254\nTraceback (most recent call last):\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/errors.py\", line 164, in __call__\n    await self.app(scope, receive, _send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 762, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 782, in app\n    await route.handle(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 297, in handle\n    await self.app(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 77, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 72, in app\n    response = await func(request)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 315, in app\n    content = await serialize_response(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 155, in serialize_response\n    raise ResponseValidationError(\nfastapi.exceptions.ResponseValidationError: 1 validation errors:\n  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': None, 'url': 'https:\/\/errors.pydantic.dev\/2.5\/v\/model_attributes_type'}\n\n\n\n"},{"result":{"nanos":108200,"errorMessage":"status code was: 500, expected: 200, response time in milliseconds: 332, url: https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/blood_type\/all\/, response: \nTraceback (most recent call last):\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/errors.py\", line 164, in __call__\n    await self.app(scope, receive, _send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 762, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 782, in app\n    await route.handle(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 297, in handle\n    await self.app(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 77, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 72, in app\n    response = await func(request)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 315, in app\n    content = await serialize_response(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 155, in serialize_response\n    raise ResponseValidationError(\nfastapi.exceptions.ResponseValidationError: 1 validation errors:\n  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': None, 'url': 'https:\/\/errors.pydantic.dev\/2.5\/v\/model_attributes_type'}\n\n\nsrc\/test\/java\/blood_type\/blood_type_all.feature:11","millis":0.1082,"status":"failed"},"step":{"line":11,"prefix":"Then","index":2,"text":"status 200"},"stepLog":"17:27:20.348 src\/test\/java\/blood_type\/blood_type_all.feature:11\nThen status 200\nstatus code was: 500, expected: 200, response time in milliseconds: 332, url: https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/blood_type\/all\/, response: \nTraceback (most recent call last):\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/errors.py\", line 164, in __call__\n    await self.app(scope, receive, _send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 762, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 782, in app\n    await route.handle(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 297, in handle\n    await self.app(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 77, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 72, in app\n    response = await func(request)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 315, in app\n    content = await serialize_response(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 155, in serialize_response\n    raise ResponseValidationError(\nfastapi.exceptions.ResponseValidationError: 1 validation errors:\n  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': None, 'url': 'https:\/\/errors.pydantic.dev\/2.5\/v\/model_attributes_type'}\n\n\nsrc\/test\/java\/blood_type\/blood_type_all.feature:11\n"}],"line":8,"description":"","durationMillis":2812.6938,"failed":true,"error":"status code was: 500, expected: 200, response time in milliseconds: 332, url: https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/blood_type\/all\/, response: \nTraceback (most recent call last):\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/errors.py\", line 164, in __call__\n    await self.app(scope, receive, _send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 762, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 782, in app\n    await route.handle(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 297, in handle\n    await self.app(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 77, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 72, in app\n    response = await func(request)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 315, in app\n    content = await serialize_response(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 155, in serialize_response\n    raise ResponseValidationError(\nfastapi.exceptions.ResponseValidationError: 1 validation errors:\n  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': None, 'url': 'https:\/\/errors.pydantic.dev\/2.5\/v\/model_attributes_type'}\n\n\nsrc\/test\/java\/blood_type\/blood_type_all.feature:11","tags":["alldays"],"executorName":"main","name":"Get all blood_type","startTime":1709591237517,"refId":"[1:8]","endTime":1709591240348,"exampleIndex":-1}],"callDepth":0,"name":"Get all blood_type on request","description":"","resultDate":"2024-03-04 05:27:20 p.\u202Fm.","durationMillis":2812.6938,"passedCount":0}